name: FireHire Discord Bot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"

      - name: Restore state cache
        uses: actions/cache@v4
        with:
          path: last_state.json
          key: firehire-state-v1
          restore-keys: firehire-state-v1

      - name: Install dependencies
        run: pip install discord.py gspread google-auth

      - name: Run check 1
        env:
          DISCORD_TOKEN:      ${{ secrets.DISCORD_TOKEN }}
          SPREADSHEET_ID:     ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python bot.py

      - name: Wait 60s
        run: sleep 60

      - name: Run check 2
        env:
          DISCORD_TOKEN:      ${{ secrets.DISCORD_TOKEN }}
          SPREADSHEET_ID:     ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python bot.py

      - name: Wait 60s
        run: sleep 60

      - name: Run check 3
        env:
          DISCORD_TOKEN:      ${{ secrets.DISCORD_TOKEN }}
          SPREADSHEET_ID:     ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python bot.py

      - name: Wait 60s
        run: sleep 60

      - name: Run check 4
        env:
          DISCORD_TOKEN:      ${{ secrets.DISCORD_TOKEN }}
          SPREADSHEET_ID:     ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python bot.py

      - name: Wait 60s
        run: sleep 60

      - name: Run check 5
        env:
          DISCORD_TOKEN:      ${{ secrets.DISCORD_TOKEN }}
          SPREADSHEET_ID:     ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python bot.py

      - name: Save state cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: last_state.json
          key: firehire-state-v1
